export enum BannerType {
    LINK_FOR_MOBILE = "LINK_FOR_MOBILE",
    BY_LINK = "BY_LINK",
    PROMOTION = "PROMOTION",
    BY_AGENT = "BY_AGENT",
    BY_TOUR_CATEGORY = "BY_TOUR_CATEGORY",
    BY_DESTINATION = "BY_DESTINATION",
    BY_TOUR = "BY_TOUR",
}
